details: 
  place: tpt
  name: teju
  age: 27
  gender: f
  city: ctr
  drink: coffee
  # country: us
  nation: uk
  color: pink

demos:
  regex:
    enabled: true

favorite:
    drink: coffee
    food: a
pizzaToppings:
  - mushrooms
  - cheese
  - peppers
  - onions
  - pineapple
